### ISSUE TITLE
Token Configuration checkboxes are clashing

### ISSUE THREAD

**Issue by mclemente** [moo-man/WFRP4e-FoundryVTT#934]
**Describe the bug**
If I set two checkbox in the Token Configuration's Position tab, the boxes clash since the CSS is set to position: absolute.

Current CSS
```css
.token-sheet .tab[data-tab="position"] input[type="checkbox"] {
    transform: scale(1);
    position: absolute;
    top: 295px;
    left: 294px;
    margin-top: 2px;
    opacity: 0.75;
    box-shadow: 0px 0px 4px inset black;
}
```

Suggested fix:
```css
.token-sheet .tab[data-tab="position"] input[type="checkbox"] {
    margin-top: 2px;
    opacity: 0.75;
    box-shadow: 0px 0px 4px inset black;
}
```

**To Reproduce**
- Install and enable the About Face module (or any module that adds a checkbox setting to the Position tab).
- Open the Token Configuration, go to the Position tab.
- Disable Direction Indicator's checkbox is over Lock Rotation's checkbox.
- Go to the Image tab and see how Mirror Image Horizontally/Vertically's checkboxes don't conflict.

**Screenshots**
How it is
![image](https://user-images.githubusercontent.com/5288872/144753824-e6dae52d-5acb-449a-92f9-527902041261.png)

How it looks with the suggested CSS
![image](https://user-images.githubusercontent.com/5288872/144753826-871751f4-9799-4feb-97e5-4481e49adf7d.png)

**Version Numbers**
FVTT 0.8.9
WFRP 4.3.0

Foundry:
wfrp4e: Yes
